base-urls:
    idam-user: ${IDAM_API_URL:http://localhost:4501}
    idam-s2s: ${S2S_URL:http://localhost:4502}
    s2s-token: ${S2S_TOKEN:AAAAAAAAAAAAAAAA}
    dm-store: ${TEST_URL:http://localhost:4603}
    large-docs: ${TEST_URL:https://www.dropbox.com/s}

toggle:
    metadatasearchendpoint: ${ENABLE_METADATA_SEARCH:true}
    documentandmetadatauploadendpoint: ${ENABLE_DOCUMENT_AND_METADATA_UPLOAD:true}
    folderendpoint: ${ENABLE_FOLDER_API:true}
    deleteenabled: ${ENABLE_DELETE:true}
    ttl: ${ENABLE_TTL:true}
    thumbnail: ${ENABLE_THUMBNAIL:true}
    includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}
    metadatamigration: ${ENABLE_METADATA_MIGRATION:false}

large-docs-ids:
    mp4-52mb: ${MP4_52MB:84t2z2zjzhhrmt5/52MB_Video.mp4?dl=1}
    mp4-111mb: ${MP4_111MB:vg5fj4tbm0o23z9/111MB_Video.mp4?dl=1}

large-docs:
    metadata:
        50f9dd86-1615-461d-bca8-e437103dd734:
            documentName: 111MB_Video
            extension: mp4
            size: 111022382

        e58a9fa5-4f6f-438f-b44a-8c0877e945d0:
            documentName: 52MB_Video
            extension: mp4
            size: 52254796
